name: Upload and Scan Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      with:
        version: 'latest'

    - name: Configure JFrog CLI
      run: |
        jfrog config add my-config \
          --url=${{ secrets.JFROG_URL }} \
          --password=${{ secrets.JFROG_API_KEY }}

    - name: Run Xray Scan (optional)
      run: |
        jf xr scan --url=${{ secrets.JF_URL }} --apikey=${{ secrets.JF_ACCESS_TOKEN }} 
