name: "Frogbot Scan Pull Request"
on:
  push:
    branches: 
    - main
permissions:
  pull-requests: write
  contents: read
jobs:
  auth:
      permissions:
          contents: read
          id-token: write
      runs-on: ubuntu-latest
      steps:
          - name: Get id token
            run: |
                ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                "${ACTIONS_ID_TOKEN_REQUEST_URL}" | jq .value | tr -d '"')
                echo "ID_TOKEN=${ID_TOKEN}" >> $GITHUB_ENV
          - name: Exchange token with access
            env:
                ID_TOKEN: ${{env.ID_TOKEN}}
                JFROG_PLATFORM_URL: https://test1233.jfrog.io
            run: |
                ACCESS_TOKEN=$(curl -XPOST -H "Content-Type: application/json" "https://test1233.jfrog.io/access/api/v1/oidc/token" -d "{\"grant_type\": \"urn:ietf:params:oauth:grant-type:token-exchange\", \"subject_token_type\":\"urn:ietf:params:oauth:token-type:id_token\", \"subject_token\": \"${ID_TOKEN}\", \"provider_name\": \"github\"}" | jq .access_token | tr -d '"')
                echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_ENV
          
  scan-pull-request:
    runs-on: ubuntu-latest
    environment: frogbot
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - uses: jfrog/setup-jfrog-cli@v3
        env:
            JF_URL: ${{ secrets.JF_URL }}
        with:
            oidc-provider-name: github
      
      - uses: jfrog/frogbot@5d9c42c30f1169d8be4ba5510b40e75ffcbbc2a9  # v2.21.2
        env:
          JF_INSTALL_DEPS_CMD: "npm install" 
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}





