name: SonarQube analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: [self-hosted, your-label]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test SonarQube Server Connectivity
        run: |
          curl -v ${{ secrets.SONAR_HOST_URL }}

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://smee.io/8ORjvW2DU0PfLkgi
        with:
          args: |
            -Dsonar.projectKey=dev-formoptix_todo_7deb2f0f-0cca-4ac0-9a00-14e09259b322
