name: SonarQube analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read  # Allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Verify secrets
        run: |
          echo "SONAR_HOST_URL is set to ${SONAR_HOST_URL:0:10}********"
          echo "SONAR_TOKEN is set to ${SONAR_TOKEN:0:10}********"
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run SonarQube scan with Docker
        run: |
          docker run --rm --network sonarqube-network -v "$(pwd)":/usr/src -w /usr/src sonarsource/sonar-scanner-cli \
          -Dsonar.projectKey=test-project \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
