name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=dev-formoptix_todo_64d15527-7df3-4387-b0c2-bfa8799e99a2
            -Dsonar.host.url=http://localhost:9000
            -Dsonar.login=sqp_151d66075f44a0afd1e95689d005d327e60fbaa0